import type { Metadata } from "next"
import { Inter } from 'next/font/google'
import "./globals.css"

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Josué Soares | Desenvolvedor Web",
  description: "Generated by Josué Soares",
  icons: {
    icon: "/favicon-brasil.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={inter.variable}>
      <body className={`antialiased ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
